
namespace ValheimDamageTypesMod.Common
{
    public static class ValheimDamageBase
    {
        [Flags]
        public enum DamageType : byte
        {
            Blunt = 1 << 0,
            Pierce = 1 << 1,
            Slash = 1 << 2,
            Fire = 1 << 3,
            Frost = 1 << 4,
            Poison = 1 << 5,
            Lightning = 1 << 6,
            Spirit = 1 << 7
        }
        public static Dictionary<int, DamageType> Projectiles = [];
        public static Dictionary<int, DamageType> NPCs = [];
        public static Dictionary<int, DamageType> Items = [];
        public static string output = "";
        public static void AssignDamage(string list, DamageType type)
        {
            foreach (var name in list.Split(' '))
            {
                output += $"\nProjectiles[ProjectileID.{name}] = DamageType.{type};";
            }
            if (list != "")
            {
                // example of code generated by the loop above:
                Projectiles[ProjectileID.FireArrow] = DamageType.Blunt, Fire;


                // example of code i need it to generate:
                Projectiles[ProjectileID.Bomb] = DamageType.Blunt | DamageType.Fire;
            }
        }
    }
}